### ISSUE TITLE
Prepare Slides for RADx Synthetic Data Webinar

### ISSUE THREAD

**Issue by matthewhorridge** [bmir-radx/radx-project#10]
These slides are due on October 2nd.

**Comment by matthewhorridge** [comment]
@marcosmro is this appropriate here?  If so, what label?

**Comment by marcosmro** [comment]
Thanks @matthewhorridge. Yes!, it's very appropriate. I've added the labels.

**Comment by matthewhorridge** [comment]
Completed and Webinar presented on October 24
