### ISSUE TITLE
create project for RADx Data Hub in BioPortal 

### ISSUE THREAD

**Issue by alexskr** [bmir-radx/radx-project#32]
Create a new project for RADx and RADx Data Hub in BioPortal and link all RADx related ontologies

**Comment by alexskr** [comment]
is it worth creating two distinct entries in projects that use BioPortal or one is sufficient?
 
https://bioportal.bioontology.org/projects/radx
https://bioportal.bioontology.org/projects/radx-hub

**Comment by marcosmro** [comment]
@alexskr one is sufficient. The domain name for the new production website will be https://radxdatahub.nih.gov/, and the system email address will be radx-datahub@nih.gov so I suggest radx-datahub or radxdatahub as the name of the BioPortal project.

**Comment by matthewhorridge** [comment]
Without the dash is better IMO

**Comment by alexskr** [comment]
updated: https://bioportal.bioontology.org/projects/radxdatahub
