### ISSUE TITLE
Propose a solution to speed up the process of ingesting updated ontologies into BioPortal 

### ISSUE THREAD

**Issue by alexskr** [bmir-radx/radx-project#37]
BioPortal has a mechanism for downloading ontology files from remote URLs and triggering a new submission when change is detected.  This process runs on a daily schedule which currently set to once-a-day.  The delay can cause a significant friction for users who need the new version of ontology/vocabulary to show up quicker in BioPortal.   We need to propose an enhancement for the BioPortal to expedite up this process.

**Comment by matthewhorridge** [comment]
I'd like to propose that we use GitHub webhooks.  GitHub can trigger a webhook event when a release is created.  I think this would be ideal.

**Comment by alexskr** [comment]
https://github.com/ncbo/ontologies_api/issues/127

**Comment by marcosmro** [comment]
I agree with @matthewhorridge

**Comment by matthewhorridge** [comment]
I think BioPortal will need to support GitHub secrets to validate pull requests were from GitHub.  See:  https://docs.github.com/en/webhooks/using-webhooks/validating-webhook-deliveries

**Comment by matthewhorridge** [comment]
Info you can provide to create a WebHook in GitHub:

<img width="785" alt="image" src="https://github.com/bmir-radx/radx-project/assets/488607/d013ee68-f709-485d-8ce5-8f0fe65a8a67">

**Comment by alexskr** [comment]
@matthewhorridge  highlighted a recurring issue concerning BioPortal caches. When a new ontology submission is made in BioPortal, end users are unable to ascertain the submission's status. The parsing process requires some time to complete, and even after its completion, the BioPortal UI does not immediately reflect the changes. It appears that BioPortal caches fail to effectively invalidate all caches linked to the recently processed ontology.

see https://github.com/ncbo/bioportal-project/issues/193

**Comment by alexskr** [comment]
new BioPortal API call to trigger remote ontology pull is deployed.
Sample GitHub actions script for triggering pull is [here](https://github.com/ncbo/ncbo_rest_sample_code/blob/master/github_actions/publish_to_bioportal.yml)

@matthewhorridge, would you like me to add GH actions to the radx ontology?
