### ISSUE TITLE
Support bulk-adding of artifacts to elements and templates for rapid template creation

### ISSUE THREAD

**Issue by muakdogan** [bmir-radx/radx-project#53]
Currently users can only add artifacts one at a time while creating elements or templates, which is time consuming. For rapid template creation, users should be able to add multiple fields and/or element to elements and templates.

**Comment by muakdogan** [comment]
Artifact selection modal is modified to support multi select, order of the selected items can be changed by drag and drop and selected items are preserved until the modal is closed so user can select artifacts from different folders or through search results.
<img width="1386" alt="Screenshot 2023-12-05 at 10 21 34 AM" src="https://github.com/bmir-radx/radx-project/assets/19971240/da70dc17-9791-42aa-a8f2-442e8415924a">

**Comment by muakdogan** [comment]
Implemented and closed with [PR#961](https://github.com/metadatacenter/cedar-template-editor/pull/961)

**Comment by muakdogan** [comment]
Implemented and closed with [PR#961](https://github.com/metadatacenter/cedar-template-editor/pull/961)

**Comment by marcosmro** [comment]
Thanks for documenting the task and for the great work @muakdogan!
