### ISSUE TITLE
Fix RADx Metadata Specification Template

### ISSUE THREAD

**Issue by marcosmro** [bmir-radx/radx-project#75]
Link to the template in CEDAR: https://cedar.metadatacenter.org/templates/edit/https:/repo.metadatacenter.org/templates/c691629c-1183-4425-9a12-26201eab1a10?folderId=https:%2F%2Frepo.metadatacenter.org%2Ffolders%2F5ac6dcb6-7a9b-4a75-a945-60ae43750953

This issue involves two tasks:

1. Fixing the template in production. (@egyedia)
2. Fixing the code that generates the template. (@matthewhorridge)

Below is additional information from Atti concerning the specific problems with the template.

--- Email from Atti on 1/18/24 ---
 
Here are some findings:
 
1. The template had two lines where the "Geopolitical region " appeared as a name for a node. However, in the instance it appeared without the trailing space. The CEE silently will disregard (with a console warning) non-present value nodes in the instance. In this case this node was deep, I suppose the CEE was not prepared for this situation. Anyways, running the validator resulted in an invalid instance. So this should be fixed. I would say the template should be fixed.

This is the validation that I used, suggested by Martin:

mvn exec:java@validate-instance -Dexec.args="/Users/egyedia/CEDAR/cedar-content-distribution/cedar-embeddable-editor-sample-templates/71/template.json /Users/egyedia/CEDAR/cedar-content-distribution/cedar-embeddable-editor-sample-templates/71/metadata.json"

Note, I fixed the template here, and now it validates.

3. The "Data Characteristics Table in Key-Value Pairs" node is an attribute-value pair, somewhere deep in the tree. This was present in the instance as:

    "Data Characteristics Table in Key-Value Pairs": [ "" ]

While the old instance editor was happy with this, CEE was failing, and entering a strange state.
I added a check to it to silently handle this empty value as well.
What both editors are handling nicely in case of an empty attribute-value type field is the empty array, so :
"Data Characteristics Table in Key-Value Pairs": []
would work for both.
Note, this does not cause a validation error.

4. The “valueConstraints” in this template all seem to not have the “valueSets” entry. This is required by the integrated-search endpoint of the terminology server. So, it will not throw a UI error, but it will be visible on the console, and the controlled fields will not have values to choose from.

The validator does not catch this error.

---

**Comment by egyedia** [comment]
Taking a closer look at this template, we also found these extra fields on the top level:
```
"multiValued": false,
"skos:prefLabel": "RADx Metadata Specification",
"skos:altLabel": [],
```

@matthewhorridge I am happy to remove these while updating the template, just let me know fi you are ok with this.

**Comment by martinjoconnor** [comment]
Our validator incorrectly allow additional unknown fields on templates and element schema artifacts. I am going to fix that.

(It is strict on the content of field schema artifacts.)

**Comment by egyedia** [comment]
Updated the template on production.

```
curl 'https://resource.metadatacenter.org/templates/https%3A%2F%2Frepo.metadatacenter.org%2Ftemplates%2Fc691629c-1183-4425-9a12-26201eab1a10' \
  -X GET -k \
  -H "Authorization: apiKey KEY" \
  | jq > 01-radx-from-production.json

curl 'https://resource.metadatacenter.org/templates/https%3A%2F%2Frepo.metadatacenter.org%2Ftemplates%2Fc691629c-1183-4425-9a12-26201eab1a10' \
  -X PUT -k \
  -d @02-template-71.json \
  -H "Authorization: apiKey KEY" \
  | jq > 03-radx-updated-on-production.json

  curl 'https://resource.metadatacenter.org/templates/https%3A%2F%2Frepo.metadatacenter.org%2Ftemplates%2Fc691629c-1183-4425-9a12-26201eab1a10' \
  -X GET -k \
  -H "Authorization: apiKey KEY" \
  | jq > 04-radx-from-production-after-update.json
```

**Comment by yancao77** [comment]
The defaultValue of Publication Date Type (a controlled term field) is incorrect. 


![Image](https://github.com/bmir-radx/radx-project/assets/131015250/bf6e85df-5257-4b8f-8bc6-4887e433e039)
